sudo: required
dist: trusty

language: node_js

node_js:
  - "4"
  - "5"

before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get install -y ethereum

before_script:
  - "npm install -g gulp"
  - "npm install"

script:
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com

